name = "cf-worker-dev"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "./dist/"
entry-point = "."

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[env.production]
name = "cf-worker"

[env.staging]
name = "cf-worker-staging"
