name = "cf-worker-dev"
main = "./dist/cf-sw.js"
workers_dev = true
compatibility_date = "2022-07-26"

[site]
bucket = "./dist/"

[build]
command = "npm run build"

[env.production]
name = "cf-worker"

[env.staging]
name = "cf-worker-staging"
